version: '3'

services:
  tomcat:
    build: ./tomcat
    ports:
      - "8000:8080"
    volumes:
      - ./tomcat/war:/usr/local/tomcat/webapps

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./nginx/pages:/var/www