<%@ page import="java.util.ArrayList, marfcat.File" language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Marfcat Input</title>
</head>
<body>
	<h1>Marfcat Input:</h1>
	<hr>
	<br>
	<h3>DataSet</h3>
	<h5>Generated By: <%= (String)request.getAttribute("dataset-generated-by") %></h5>
	<h5>Generated On: <%= (String)request.getAttribute("dataset-generated-on") %></h5>
	<br>
	<h3>Description</h3>
	<h5>File Type Tool: <%= (String)request.getAttribute("description-file-type-tool") %></h5>
	<h5>Find Tool: <%= (String)request.getAttribute("description-find-tool") %></h5>
	<h5>Marfcat Tool: <%= (String)request.getAttribute("description-marfcat-tool") %></h5>
	<br>
	<hr>
	<br>
	<h3>Files</h3>
	<% ArrayList<File> files = (ArrayList<File>)request.getAttribute("files"); %>
	<% for(File f : files) { %>
	<hr>
	<h5>File ID: <%= f.id %></h5>
	<h5>File path: <%= f.path %></h5>
	<h5>Type: <%= f.meta.type %></h5>
	<h5>Number of lines: <%= f.meta.length.lines %></h5>
	<h5>Number of words: <%= f.meta.length.words %></h5>
	<h5>Number of bytes: <%= f.meta.length.bytes %></h5>
	<h5>Location line: <%= f.location.line %></h5>
	<h5>Location fraglines: <%= f.location.fraglines %></h5>
	<h5>Location fragment: <%= f.location.fragment %></h5>
	<h5>Location explanation: <%= f.location.explanation %></h5>
	<% } %>
</body>
</html>