<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Marfact Input</title>
</head>
<body>
	<h1>Marfact Input:</h1>
	<hr>
	<br>
	<h3>DataSet</h3>
	<h5>Generated By: <%= (String)request.getAttribute("dataset-generated-by") %></h5>
	<h5>Generated On: <%= (String)request.getAttribute("dataset-generated-on") %></h5>
	<br>
	<h3>Description</h3>
	<h5>File Type Tool: <%= (String)request.getAttribute("description-file-type-tool") %></h5>
	<h5>Find Tool: <%= (String)request.getAttribute("description-find-tool") %></h5>
	<h5>Marfcat Tool: <%= (String)request.getAttribute("description-marfcat-tool") %></h5>
	<br>
	<hr>
	<br>
	<h3>File</h3>
	<h5>File ID: <%= (String)request.getAttribute("file-id") %></h5>
	<h5>File path: <%= (String)request.getAttribute("file-path") %></h5>
	<h5>Type: <%= (String)request.getAttribute("meta-type") %></h5>
	<h5>Number of lines: <%= (String)request.getAttribute("number-lines") %></h5>
	<h5>Number of words: <%= (String)request.getAttribute("number-words") %></h5>
	<h5>Number of bytes: <%= (String)request.getAttribute("number-bytes") %></h5>
	<h5>Location line: <%= (String)request.getAttribute("location-line") %></h5>
	<h5>Location fraglines: <%= (String)request.getAttribute("mlocation-fraglines") %></h5>
	<h5>Location fragment: <%= (String)request.getAttribute("location-fragment") %></h5>
	<h5>Location explanation: <%= (String)request.getAttribute("location-explanation") %></h5>
</body>
</html>